<a href="https://colab.research.google.com/github/3C37/3C37-s-Storage/blob/main/02_TF_Perceptron.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 퍼셉트론(Perceptron)

In [ ]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt

## Perceptron Operation

In [ ]:
## data 선언
x_data =[[1.],[2.],[3.]]
y_data =[[1.],[2.],[3.]]

## 평균 0, 분산 1의 파라미터의 정규분포로 부터 값을 가져옴.
# 학습을 통해 업데이트가 되어 변화되는 모델의 파라미터인 w,b를 의미한다.
W=tf.Variable(tf.random.normal((1,1), mean=1, stddev=0.5))
b=tf.Variable(tf.random.normal((1,1), mean=1, stddev=0.5))
print("W : ", W)
print("b : ", b)

for j in range(len(x_data)):
    ## data * weight
    WX =tf.matmul([x_data[j]], W)

    ## bias add
    y_hat = tf.add(WX, b)

    ## W와 b로 예측 하기
    print("y_data: , ",y_data[j], "prediction : ", y_hat)

W :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.930828]], dtype=float32)>
b :  <tf.Variable 'Variable:0' shape=(1, 1) dtype=float32, numpy=array([[0.68094915]], dtype=float32)>
y_data: ,  [1.0] prediction :  tf.Tensor([[1.6117771]], shape=(1, 1), dtype=float32)
y_data: ,  [2.0] prediction :  tf.Tensor([[2.5426052]], shape=(1, 1), dtype=float32)
y_data: ,  [3.0] prediction :  tf.Tensor([[3.473433]], shape=(1, 1), dtype=float32)


## 논리 게이트

In [ ]:
def activation(x):
    return tf.cast((x > 0), dtype=tf.float32)

# AND 게이트 함수 정의
def AND(x, w, b):
    z = tf.math.reduce_sum(w * x) + b           
    a = activation(z)
    return a

# NAND 게이트 함수 정의
def NAND(x, w, b):
    z = tf.math.reduce_sum(w * x) + b
    a = activation(z)
    return a

# AND 게이트 함수 정의
def OR(x, w, b):
    z = tf.math.reduce_sum(w * x) + b
    a = activation(z)
    return a

# 각 게이트에 알맞는 w, b 가중치 생성
w_and = tf.Variable([0.5, 0.5])  
b_and = tf.Variable([-0.7])
w_nand = tf.Variable([-0.5, -0.5])  
b_nand = tf.Variable([0.7])
w_or = tf.Variable([0.5, 0.5]) 
b_or = tf.Variable([-0.2])

# 입력 텐서를 만들어 결과 확인
X = tf.constant([[0, 0], [0, 1], [1, 0], [1, 1]], dtype=tf.float32)
for x in X:
    print(f"input : {x}")
    print(" - AND:", AND(x, w=w_and, b=b_and).numpy())
    print(" - NAND:", NAND(x, w=w_nand, b=b_nand).numpy())
    print(" - OR:", OR(x, w=w_or, b=b_or).numpy())
    print("--"*15)

input : [0. 0.]
 - AND: [0.]
 - NAND: [1.]
 - OR: [0.]
------------------------------
input : [0. 1.]
 - AND: [0.]
 - NAND: [1.]
 - OR: [1.]
------------------------------
input : [1. 0.]
 - AND: [0.]
 - NAND: [1.]
 - OR: [1.]
------------------------------
input : [1. 1.]
 - AND: [1.]
 - NAND: [0.]
 - OR: [1.]
------------------------------


## XOR 문제

In [ ]:
def solution(x, **kwargs):

    # 정답을 작성해주세요.
    
    # 새로운 층
    s1 = NAND(x, w=kwargs['w_nand'], b=kwargs['b_nand'])
    s2 = OR(x, w=kwargs['w_or'], b=kwargs['b_or'])
    
    # 출력 층: s1 과 s2 를 새로운 입력으로 구성하여 전달
    x = tf.concat([s1, s2], axis = 0)
    y = AND(x = x, w=kwargs['w_and'], b=kwargs['b_and'])

    return y

# 입력 텐서와 타겟 텐서를 생성
input_data = tf.constant([[0, 0], [1, 0], [0, 1], [1, 1]], dtype=tf.float32)
target_data = tf.constant([0, 1, 1, 0], dtype=tf.float32)

# 이전에 사용한 가중치를 dictionary 타입으로 만든다.
kwargs = dict([('w_nand', w_nand), ('b_nand', b_nand), 
               ('w_or', w_or), ('b_or', b_or), 
               ('w_and', w_and), ('b_and', b_and)])

# 테스트
for x, y in zip(input_data, target_data):
    pred = solution(x, **kwargs)
    print(f"predict: {pred.numpy()} | target: {y.numpy()}")

predict: [0.] | target: 0.0
predict: [1.] | target: 1.0
predict: [1.] | target: 1.0
predict: [0.] | target: 0.0
